# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_auto_20161211_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activ',
            options={'verbose_name': 'Activ', 'verbose_name_plural': 'Activs'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='lifecycle',
            options={'verbose_name': 'Life cycle', 'verbose_name_plural': 'Life cycles'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Request', 'verbose_name_plural': 'Requests'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='activ',
            name='cub_number',
            field=models.CharField(max_length=50, verbose_name='cabinet number'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='lifecycle',
            name='checking',
            field=models.DateField(null=True, verbose_name='checking'),
        ),
        migrations.AlterField(
            model_name='lifecycle',
            name='closed',
            field=models.DateField(null=True, verbose_name='closed'),
        ),
        migrations.AlterField(
            model_name='lifecycle',
            name='distributed',
            field=models.DateField(null=True, verbose_name='dustributed'),
        ),
        migrations.AlterField(
            model_name='lifecycle',
            name='opened',
            field=models.DateField(auto_now_add=True, verbose_name='opened'),
        ),
        migrations.AlterField(
            model_name='lifecycle',
            name='proccesing',
            field=models.DateField(null=True, verbose_name='proccesing'),
        ),
        migrations.AlterField(
            model_name='request',
            name='comment',
            field=models.CharField(max_length=200, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.CharField(max_length=200, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='request',
            name='priority',
            field=models.IntegerField(verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
